INSERT INTO theater_entity (id, name,seats_max) VALUES (1, 'Sal 1', 20);
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'A1');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'A2');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'A3');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'A4');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'A5');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'B1');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'B2');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'B3');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'B4');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'B5');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'C1');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'C2');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'C3');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'C4');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'C5');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'D1');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'D2');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'D3');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'D4');
INSERT INTO theater_entity_seats (theater_entity_id, seats) VALUES (1, 'D5');


INSERT INTO show_entity (id, cinema_id, movie_id, start_time) VALUES (1, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'A1');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'A2');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'A3');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'A4');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'A5');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'B1');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'B2');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'B3');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'B4');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'B5');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'C1');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'C2');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'C3');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'C4');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'C5');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'D1');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'D2');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'D3');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'D4');
INSERT INTO show_entity_seats (show_entity_id, seats) VALUES (1, 'D5');