spring:
  application:
    name: gateway
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
            - HEAD
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/v1/users/**
        filters:
        - StripPrefix=2
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/api/v1/auth/**
        filters:
        - StripPrefix=3
      - id: kino-service
        uri: lb://kino-service
        predicates:
        - Path=/api/v1/kino/**
        filters:
        - StripPrefix=3
      - id: ticket-service
        uri: lb://ticket-service
        predicates:
        - Path=/api/v1/tickets/**
        filters:
        - StripPrefix=2
      - id: movie-service
        uri: lb://movie-service
        predicates:
        - Path=/api/v1/movies/**
        filters:
        - StripPrefix=2
      - id: booking-service
        uri: lb://booking-service
        predicates:
        - Path=/api/v1/orders/**
        filters:
        - StripPrefix=2
      - id: frontend
        uri: lb://frontend
        predicates:
        - Path=/**
        filters:
        - StripPrefix=0

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/