create sequence hibernate_sequence start with 1 increment by 1;
create table movie_entity (id bigint generated by default as identity, description varchar(500), featured boolean not null, image_path varchar(255), release_date timestamp not null, title varchar(255), primary key (id))
