export const AUTHENTICATED = 'USER_AUTHENTICATED';
export const NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';
export const REQUIRES_AUTHENTICATION = 'USER_AUTHENTICATED_REQUIRED';
export const MOVIE_UPDATED = 'MOVIE_UPDATED';